# Generated by Django 6.0.7 on 2026-07-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusModel',
            new_name='Status',
        ),
    ]
