# Generated by Django 6.0.7 on 2026-08-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltask',
            name='label',
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='labeltask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='LabelTask',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
