name: Task Manager CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'test-secret-key'
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

        # make depends on uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: |
          make lint

      - name: Run tests
        run: |
          make test

      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Irina-Grebennikova_python-project-52
            -Dsonar.organization=girishkaizh
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=**/tests/**,**/migrations/**,manage.py,**/asgi.py,**/wsgi.py
            -Dsonar.exclusions=**/tests/**,**/migrations/**
